// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      id: json['id'] as int?,
      fName: json['f_name'] as String?,
      lName: json['l_name'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      image: json['image'] as String?,
      isPhoneVerified: json['is_phone_verified'] as int?,
      isEmailVerified: json['is_email_verified'] as int?,
      emailVerifiedAt: json['email_verified_at'] as String?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      cmFirebaseToken: json['cm_firebase_token'] as String?,
      status: json['status'] as int?,
      orderCount: json['order_count'] as int?,
      loginMedium: json['login_medium'],
      socialId: json['social_id'],
      zoneId: json['zone_id'],
      walletBalance: json['wallet_balance'] as int?,
      loyaltyPoint: json['loyalty_point'] as int?,
      refCode: json['ref_code'] as String?,
      accessToken: json['access_token'] as String?,
      appleProviderId: json['apple_provider_id'] as String?,
      facebookProviderId: json['facebook_provider_id'] as String?,
      googleProviderId: json['google_provider_id'] as String?,
      socialProviderName: json['social_provider_name'] as String?,
      active: json['active'] as int?,
      earning: json['earning'] as int?,
      currentOrders: json['current_orders'] as int?,
      type: json['type'] as String?,
      applicationStatus: json['application_status'] as String?,
      assignedOrderCount: json['assigned_order_count'] as int?,
      isServiceMen: json['is_service_men'] as int?,
      serviceMenKyc: json['service_men_kyc'] as int?,
      artisanServiceAvailable: json['artisan_service_available'] as int?,
      registrationType: json['registration_type'] as String?,
      companyName: json['company_name'] as String?,
      companyPhone: json['company_phone'] as String?,
      companyEmail: json['company_email'] as String?,
      companyLogo: json['company_logo'] as String?,
      companyAddress: json['company_address'] as String?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'id': instance.id,
      'f_name': instance.fName,
      'l_name': instance.lName,
      'phone': instance.phone,
      'email': instance.email,
      'image': instance.image,
      'is_phone_verified': instance.isPhoneVerified,
      'is_email_verified': instance.isEmailVerified,
      'email_verified_at': instance.emailVerifiedAt,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'cm_firebase_token': instance.cmFirebaseToken,
      'status': instance.status,
      'order_count': instance.orderCount,
      'login_medium': instance.loginMedium,
      'social_id': instance.socialId,
      'zone_id': instance.zoneId,
      'wallet_balance': instance.walletBalance,
      'loyalty_point': instance.loyaltyPoint,
      'ref_code': instance.refCode,
      'access_token': instance.accessToken,
      'apple_provider_id': instance.appleProviderId,
      'facebook_provider_id': instance.facebookProviderId,
      'google_provider_id': instance.googleProviderId,
      'social_provider_name': instance.socialProviderName,
      'active': instance.active,
      'earning': instance.earning,
      'current_orders': instance.currentOrders,
      'type': instance.type,
      'application_status': instance.applicationStatus,
      'assigned_order_count': instance.assignedOrderCount,
      'is_service_men': instance.isServiceMen,
      'service_men_kyc': instance.serviceMenKyc,
      'artisan_service_available': instance.artisanServiceAvailable,
      'registration_type': instance.registrationType,
      'company_name': instance.companyName,
      'company_phone': instance.companyPhone,
      'company_email': instance.companyEmail,
      'company_logo': instance.companyLogo,
      'company_address': instance.companyAddress,
    };
