name: kabor
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  app_models:
    path: ../packages/app_models
  chat_bubbles: ^1.3.1
  customer_authentication_repository:
    path: ../packages/customer_authentication_repository
  dio: ^5.1.1
  equatable: ^2.0.5
  kcabor_storage:
    path: ../packages/kcabor_storage
  flutter:
    sdk: flutter
  fl_chart: ^0.55.2
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  geolocator: ^9.0.2
  go_router: ^5.1.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_place: ^0.4.7
  hooks_riverpod: ^2.0.1
  iconsax: ^0.0.8
  intl: ^0.17.0
  image_picker: ^0.8.7
  location: ^4.4.0
  mime_type: ^1.0.0
  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  rxdart: ^0.27.5
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_datepicker: ^20.3.59
  timelines: ^0.1.0
  date_field: ^3.0.2
  adaptive_dialog: ^1.8.0+1
  syncfusion_flutter_barcodes: ^20.3.61
  share_plus: ^6.3.0
  http: ^0.13.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  intl_phone_number_input: ^0.7.2
  riverpod_annotation: ^1.2.1
  another_flushbar: ^1.12.29
  http_interceptor: ^1.0.2
  smooth_infinite_scroll: ^0.1.2+1
  shimmer: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  custom_lint: ^0.2.5
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  riverpod_generator: ^1.2.0
  riverpod_lint: ^1.0.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
